Fix the build when using python3 - print needs parentheses
Trival fix for this failure...

*** Error compiling '.../usr/lib/python3.6/site-packages/rmtest/disposableredis/cluster.py'...
  File "/usr/lib/python3.6/cluster.py", line 70
    print "All nodes OK!"
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "All nodes OK!")?